//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmpID { get; set; }
        public string EmpFName { get; set; }
        public string EmpMName { get; set; }
        public string EmpLName { get; set; }
        public string EmpContactNumber { get; set; }
        public string EmpAddress { get; set; }

        public string EmpEncryptedString{ get; set; }
    }
}
